# Generated by Django on data migration
from django.db import migrations

def seed_legacy_accounts(apps, schema_editor):
    Company = apps.get_model('myapp', 'Company')
    Employee = apps.get_model('myapp', 'Employee')

    co_email = 'nsb566@gmail.com'.strip().lower()
    emp_email = 'nsb566@gmail.com'.strip().lower()

    company = Company.objects.filter(email__iexact=co_email).first()
    if not company:
        company = Company.objects.create(
            name='Teamnexttest',
            email=co_email,
            password='Sid878806',
            address='None',
            phone='8788067098',
            website='None',
            employees_count='None',
            industry=''
        )

    employee = Employee.objects.filter(email__iexact=emp_email).first()
    if not employee:
        Employee.objects.create(
            company=company,
            name='Teamnexttest',
            email=emp_email,
            password='Sid878806',
            role='Administrator',
            department_old='None',
            phone='None'
        )

def unseed_legacy_accounts(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_legacy_accounts, unseed_legacy_accounts),
    ]
